name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Archive Pork Bundle
        uses: actions/upload-artifact@v3
        with:
          name: pork-bundle
          path: tool/build/distributions/pork.zip
      - name: Archive Pork Jar
        uses: actions/upload-artifact@v3
        with:
          name: pork-jar
          path: tool/build/distributions/pork-all.jar
